/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaTherapyLabRouteImport } from './routes/yoga-therapy-lab'
import { Route as TaiChiLabRouteImport } from './routes/tai-chi-lab'
import { Route as SmoothieCodexRouteImport } from './routes/smoothie-codex'
import { Route as SkillTreesRouteImport } from './routes/skill-trees'
import { Route as SanctuaryRouteImport } from './routes/sanctuary'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AlchemistsPathRouteImport } from './routes/alchemists-path'
import { Route as IndexRouteImport } from './routes/index'

const YogaTherapyLabRoute = YogaTherapyLabRouteImport.update({
  id: '/yoga-therapy-lab',
  path: '/yoga-therapy-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiChiLabRoute = TaiChiLabRouteImport.update({
  id: '/tai-chi-lab',
  path: '/tai-chi-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoothieCodexRoute = SmoothieCodexRouteImport.update({
  id: '/smoothie-codex',
  path: '/smoothie-codex',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTreesRoute = SkillTreesRouteImport.update({
  id: '/skill-trees',
  path: '/skill-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctuaryRoute = SanctuaryRouteImport.update({
  id: '/sanctuary',
  path: '/sanctuary',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AlchemistsPathRoute = AlchemistsPathRouteImport.update({
  id: '/alchemists-path',
  path: '/alchemists-path',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alchemists-path'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga-therapy-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alchemists-path'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga-therapy-lab'
  id:
    | '__root__'
    | '/'
    | '/alchemists-path'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga-therapy-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlchemistsPathRoute: typeof AlchemistsPathRoute
  CommunityRoute: typeof CommunityRoute
  LibraryRoute: typeof LibraryRoute
  QuestsRoute: typeof QuestsRoute
  SanctuaryRoute: typeof SanctuaryRoute
  SkillTreesRoute: typeof SkillTreesRoute
  SmoothieCodexRoute: typeof SmoothieCodexRoute
  TaiChiLabRoute: typeof TaiChiLabRoute
  YogaTherapyLabRoute: typeof YogaTherapyLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga-therapy-lab': {
      id: '/yoga-therapy-lab'
      path: '/yoga-therapy-lab'
      fullPath: '/yoga-therapy-lab'
      preLoaderRoute: typeof YogaTherapyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-chi-lab': {
      id: '/tai-chi-lab'
      path: '/tai-chi-lab'
      fullPath: '/tai-chi-lab'
      preLoaderRoute: typeof TaiChiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoothie-codex': {
      id: '/smoothie-codex'
      path: '/smoothie-codex'
      fullPath: '/smoothie-codex'
      preLoaderRoute: typeof SmoothieCodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-trees': {
      id: '/skill-trees'
      path: '/skill-trees'
      fullPath: '/skill-trees'
      preLoaderRoute: typeof SkillTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctuary': {
      id: '/sanctuary'
      path: '/sanctuary'
      fullPath: '/sanctuary'
      preLoaderRoute: typeof SanctuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alchemists-path': {
      id: '/alchemists-path'
      path: '/alchemists-path'
      fullPath: '/alchemists-path'
      preLoaderRoute: typeof AlchemistsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlchemistsPathRoute: AlchemistsPathRoute,
  CommunityRoute: CommunityRoute,
  LibraryRoute: LibraryRoute,
  QuestsRoute: QuestsRoute,
  SanctuaryRoute: SanctuaryRoute,
  SkillTreesRoute: SkillTreesRoute,
  SmoothieCodexRoute: SmoothieCodexRoute,
  TaiChiLabRoute: TaiChiLabRoute,
  YogaTherapyLabRoute: YogaTherapyLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
