/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaTherapyLabRouteImport } from './routes/yoga-therapy-lab'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as TaiChiLabRouteImport } from './routes/tai-chi-lab'
import { Route as SmoothieCodexRouteImport } from './routes/smoothie-codex'
import { Route as SkillTreesRouteImport } from './routes/skill-trees'
import { Route as SanctuaryRouteImport } from './routes/sanctuary'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BreathworkRouteImport } from './routes/breathwork'
import { Route as AlchemistsPathRouteImport } from './routes/alchemists-path'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YogaToolsRouteImport } from './routes/yoga.tools'
import { Route as YogaStartHereRouteImport } from './routes/yoga.start-here'
import { Route as YogaResourcesRouteImport } from './routes/yoga.resources'
import { Route as YogaPranayamaRouteImport } from './routes/yoga.pranayama'
import { Route as YogaPhilosophyRouteImport } from './routes/yoga.philosophy'
import { Route as YogaMasteryRouteImport } from './routes/yoga.mastery'
import { Route as YogaGoalsRouteImport } from './routes/yoga.goals'
import { Route as YogaCommunityRouteImport } from './routes/yoga.community'
import { Route as YogaAsanasRouteImport } from './routes/yoga.asanas'
import { Route as YogaAnatomyRouteImport } from './routes/yoga.anatomy'
import { Route as BreathworkToolsRouteImport } from './routes/breathwork.tools'
import { Route as BreathworkTechniquesRouteImport } from './routes/breathwork.techniques'
import { Route as BreathworkStartHereRouteImport } from './routes/breathwork.start-here'
import { Route as BreathworkScienceRouteImport } from './routes/breathwork.science'
import { Route as BreathworkResourcesRouteImport } from './routes/breathwork.resources'
import { Route as BreathworkMasteryRouteImport } from './routes/breathwork.mastery'
import { Route as BreathworkGoalsRouteImport } from './routes/breathwork.goals'
import { Route as BreathworkCommunityRouteImport } from './routes/breathwork.community'
import { Route as BreathworkAboutRouteImport } from './routes/breathwork.about'
import { Route as YogaGoalsGoalIdRouteImport } from './routes/yoga.goals.$goalId'
import { Route as YogaAsanasSlugRouteImport } from './routes/yoga.asanas.$slug'
import { Route as BreathworkTechniquesTraditionsRouteImport } from './routes/breathwork.techniques.traditions'
import { Route as BreathworkTechniquesSlugRouteImport } from './routes/breathwork.techniques.$slug'
import { Route as BreathworkGoalsGoalIdRouteImport } from './routes/breathwork.goals.$goalId'

const YogaTherapyLabRoute = YogaTherapyLabRouteImport.update({
  id: '/yoga-therapy-lab',
  path: '/yoga-therapy-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiChiLabRoute = TaiChiLabRouteImport.update({
  id: '/tai-chi-lab',
  path: '/tai-chi-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoothieCodexRoute = SmoothieCodexRouteImport.update({
  id: '/smoothie-codex',
  path: '/smoothie-codex',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTreesRoute = SkillTreesRouteImport.update({
  id: '/skill-trees',
  path: '/skill-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctuaryRoute = SanctuaryRouteImport.update({
  id: '/sanctuary',
  path: '/sanctuary',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BreathworkRoute = BreathworkRouteImport.update({
  id: '/breathwork',
  path: '/breathwork',
  getParentRoute: () => rootRouteImport,
} as any)
const AlchemistsPathRoute = AlchemistsPathRouteImport.update({
  id: '/alchemists-path',
  path: '/alchemists-path',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaToolsRoute = YogaToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => YogaRoute,
} as any)
const YogaStartHereRoute = YogaStartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => YogaRoute,
} as any)
const YogaResourcesRoute = YogaResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => YogaRoute,
} as any)
const YogaPranayamaRoute = YogaPranayamaRouteImport.update({
  id: '/pranayama',
  path: '/pranayama',
  getParentRoute: () => YogaRoute,
} as any)
const YogaPhilosophyRoute = YogaPhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => YogaRoute,
} as any)
const YogaMasteryRoute = YogaMasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => YogaRoute,
} as any)
const YogaGoalsRoute = YogaGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => YogaRoute,
} as any)
const YogaCommunityRoute = YogaCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => YogaRoute,
} as any)
const YogaAsanasRoute = YogaAsanasRouteImport.update({
  id: '/asanas',
  path: '/asanas',
  getParentRoute: () => YogaRoute,
} as any)
const YogaAnatomyRoute = YogaAnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => YogaRoute,
} as any)
const BreathworkToolsRoute = BreathworkToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkTechniquesRoute = BreathworkTechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkStartHereRoute = BreathworkStartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkScienceRoute = BreathworkScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkResourcesRoute = BreathworkResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkMasteryRoute = BreathworkMasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkGoalsRoute = BreathworkGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkCommunityRoute = BreathworkCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => BreathworkRoute,
} as any)
const BreathworkAboutRoute = BreathworkAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BreathworkRoute,
} as any)
const YogaGoalsGoalIdRoute = YogaGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => YogaGoalsRoute,
} as any)
const YogaAsanasSlugRoute = YogaAsanasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => YogaAsanasRoute,
} as any)
const BreathworkTechniquesTraditionsRoute =
  BreathworkTechniquesTraditionsRouteImport.update({
    id: '/traditions',
    path: '/traditions',
    getParentRoute: () => BreathworkTechniquesRoute,
  } as any)
const BreathworkTechniquesSlugRoute =
  BreathworkTechniquesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => BreathworkTechniquesRoute,
  } as any)
const BreathworkGoalsGoalIdRoute = BreathworkGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => BreathworkGoalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/breathwork': typeof BreathworkRouteWithChildren
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga': typeof YogaRouteWithChildren
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
  '/breathwork/about': typeof BreathworkAboutRoute
  '/breathwork/community': typeof BreathworkCommunityRoute
  '/breathwork/goals': typeof BreathworkGoalsRouteWithChildren
  '/breathwork/mastery': typeof BreathworkMasteryRoute
  '/breathwork/resources': typeof BreathworkResourcesRoute
  '/breathwork/science': typeof BreathworkScienceRoute
  '/breathwork/start-here': typeof BreathworkStartHereRoute
  '/breathwork/techniques': typeof BreathworkTechniquesRouteWithChildren
  '/breathwork/tools': typeof BreathworkToolsRoute
  '/yoga/anatomy': typeof YogaAnatomyRoute
  '/yoga/asanas': typeof YogaAsanasRouteWithChildren
  '/yoga/community': typeof YogaCommunityRoute
  '/yoga/goals': typeof YogaGoalsRouteWithChildren
  '/yoga/mastery': typeof YogaMasteryRoute
  '/yoga/philosophy': typeof YogaPhilosophyRoute
  '/yoga/pranayama': typeof YogaPranayamaRoute
  '/yoga/resources': typeof YogaResourcesRoute
  '/yoga/start-here': typeof YogaStartHereRoute
  '/yoga/tools': typeof YogaToolsRoute
  '/breathwork/goals/$goalId': typeof BreathworkGoalsGoalIdRoute
  '/breathwork/techniques/$slug': typeof BreathworkTechniquesSlugRoute
  '/breathwork/techniques/traditions': typeof BreathworkTechniquesTraditionsRoute
  '/yoga/asanas/$slug': typeof YogaAsanasSlugRoute
  '/yoga/goals/$goalId': typeof YogaGoalsGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/breathwork': typeof BreathworkRouteWithChildren
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga': typeof YogaRouteWithChildren
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
  '/breathwork/about': typeof BreathworkAboutRoute
  '/breathwork/community': typeof BreathworkCommunityRoute
  '/breathwork/goals': typeof BreathworkGoalsRouteWithChildren
  '/breathwork/mastery': typeof BreathworkMasteryRoute
  '/breathwork/resources': typeof BreathworkResourcesRoute
  '/breathwork/science': typeof BreathworkScienceRoute
  '/breathwork/start-here': typeof BreathworkStartHereRoute
  '/breathwork/techniques': typeof BreathworkTechniquesRouteWithChildren
  '/breathwork/tools': typeof BreathworkToolsRoute
  '/yoga/anatomy': typeof YogaAnatomyRoute
  '/yoga/asanas': typeof YogaAsanasRouteWithChildren
  '/yoga/community': typeof YogaCommunityRoute
  '/yoga/goals': typeof YogaGoalsRouteWithChildren
  '/yoga/mastery': typeof YogaMasteryRoute
  '/yoga/philosophy': typeof YogaPhilosophyRoute
  '/yoga/pranayama': typeof YogaPranayamaRoute
  '/yoga/resources': typeof YogaResourcesRoute
  '/yoga/start-here': typeof YogaStartHereRoute
  '/yoga/tools': typeof YogaToolsRoute
  '/breathwork/goals/$goalId': typeof BreathworkGoalsGoalIdRoute
  '/breathwork/techniques/$slug': typeof BreathworkTechniquesSlugRoute
  '/breathwork/techniques/traditions': typeof BreathworkTechniquesTraditionsRoute
  '/yoga/asanas/$slug': typeof YogaAsanasSlugRoute
  '/yoga/goals/$goalId': typeof YogaGoalsGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alchemists-path': typeof AlchemistsPathRoute
  '/breathwork': typeof BreathworkRouteWithChildren
  '/community': typeof CommunityRoute
  '/library': typeof LibraryRoute
  '/quests': typeof QuestsRoute
  '/sanctuary': typeof SanctuaryRoute
  '/skill-trees': typeof SkillTreesRoute
  '/smoothie-codex': typeof SmoothieCodexRoute
  '/tai-chi-lab': typeof TaiChiLabRoute
  '/yoga': typeof YogaRouteWithChildren
  '/yoga-therapy-lab': typeof YogaTherapyLabRoute
  '/breathwork/about': typeof BreathworkAboutRoute
  '/breathwork/community': typeof BreathworkCommunityRoute
  '/breathwork/goals': typeof BreathworkGoalsRouteWithChildren
  '/breathwork/mastery': typeof BreathworkMasteryRoute
  '/breathwork/resources': typeof BreathworkResourcesRoute
  '/breathwork/science': typeof BreathworkScienceRoute
  '/breathwork/start-here': typeof BreathworkStartHereRoute
  '/breathwork/techniques': typeof BreathworkTechniquesRouteWithChildren
  '/breathwork/tools': typeof BreathworkToolsRoute
  '/yoga/anatomy': typeof YogaAnatomyRoute
  '/yoga/asanas': typeof YogaAsanasRouteWithChildren
  '/yoga/community': typeof YogaCommunityRoute
  '/yoga/goals': typeof YogaGoalsRouteWithChildren
  '/yoga/mastery': typeof YogaMasteryRoute
  '/yoga/philosophy': typeof YogaPhilosophyRoute
  '/yoga/pranayama': typeof YogaPranayamaRoute
  '/yoga/resources': typeof YogaResourcesRoute
  '/yoga/start-here': typeof YogaStartHereRoute
  '/yoga/tools': typeof YogaToolsRoute
  '/breathwork/goals/$goalId': typeof BreathworkGoalsGoalIdRoute
  '/breathwork/techniques/$slug': typeof BreathworkTechniquesSlugRoute
  '/breathwork/techniques/traditions': typeof BreathworkTechniquesTraditionsRoute
  '/yoga/asanas/$slug': typeof YogaAsanasSlugRoute
  '/yoga/goals/$goalId': typeof YogaGoalsGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alchemists-path'
    | '/breathwork'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga'
    | '/yoga-therapy-lab'
    | '/breathwork/about'
    | '/breathwork/community'
    | '/breathwork/goals'
    | '/breathwork/mastery'
    | '/breathwork/resources'
    | '/breathwork/science'
    | '/breathwork/start-here'
    | '/breathwork/techniques'
    | '/breathwork/tools'
    | '/yoga/anatomy'
    | '/yoga/asanas'
    | '/yoga/community'
    | '/yoga/goals'
    | '/yoga/mastery'
    | '/yoga/philosophy'
    | '/yoga/pranayama'
    | '/yoga/resources'
    | '/yoga/start-here'
    | '/yoga/tools'
    | '/breathwork/goals/$goalId'
    | '/breathwork/techniques/$slug'
    | '/breathwork/techniques/traditions'
    | '/yoga/asanas/$slug'
    | '/yoga/goals/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alchemists-path'
    | '/breathwork'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga'
    | '/yoga-therapy-lab'
    | '/breathwork/about'
    | '/breathwork/community'
    | '/breathwork/goals'
    | '/breathwork/mastery'
    | '/breathwork/resources'
    | '/breathwork/science'
    | '/breathwork/start-here'
    | '/breathwork/techniques'
    | '/breathwork/tools'
    | '/yoga/anatomy'
    | '/yoga/asanas'
    | '/yoga/community'
    | '/yoga/goals'
    | '/yoga/mastery'
    | '/yoga/philosophy'
    | '/yoga/pranayama'
    | '/yoga/resources'
    | '/yoga/start-here'
    | '/yoga/tools'
    | '/breathwork/goals/$goalId'
    | '/breathwork/techniques/$slug'
    | '/breathwork/techniques/traditions'
    | '/yoga/asanas/$slug'
    | '/yoga/goals/$goalId'
  id:
    | '__root__'
    | '/'
    | '/alchemists-path'
    | '/breathwork'
    | '/community'
    | '/library'
    | '/quests'
    | '/sanctuary'
    | '/skill-trees'
    | '/smoothie-codex'
    | '/tai-chi-lab'
    | '/yoga'
    | '/yoga-therapy-lab'
    | '/breathwork/about'
    | '/breathwork/community'
    | '/breathwork/goals'
    | '/breathwork/mastery'
    | '/breathwork/resources'
    | '/breathwork/science'
    | '/breathwork/start-here'
    | '/breathwork/techniques'
    | '/breathwork/tools'
    | '/yoga/anatomy'
    | '/yoga/asanas'
    | '/yoga/community'
    | '/yoga/goals'
    | '/yoga/mastery'
    | '/yoga/philosophy'
    | '/yoga/pranayama'
    | '/yoga/resources'
    | '/yoga/start-here'
    | '/yoga/tools'
    | '/breathwork/goals/$goalId'
    | '/breathwork/techniques/$slug'
    | '/breathwork/techniques/traditions'
    | '/yoga/asanas/$slug'
    | '/yoga/goals/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlchemistsPathRoute: typeof AlchemistsPathRoute
  BreathworkRoute: typeof BreathworkRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  LibraryRoute: typeof LibraryRoute
  QuestsRoute: typeof QuestsRoute
  SanctuaryRoute: typeof SanctuaryRoute
  SkillTreesRoute: typeof SkillTreesRoute
  SmoothieCodexRoute: typeof SmoothieCodexRoute
  TaiChiLabRoute: typeof TaiChiLabRoute
  YogaRoute: typeof YogaRouteWithChildren
  YogaTherapyLabRoute: typeof YogaTherapyLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga-therapy-lab': {
      id: '/yoga-therapy-lab'
      path: '/yoga-therapy-lab'
      fullPath: '/yoga-therapy-lab'
      preLoaderRoute: typeof YogaTherapyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-chi-lab': {
      id: '/tai-chi-lab'
      path: '/tai-chi-lab'
      fullPath: '/tai-chi-lab'
      preLoaderRoute: typeof TaiChiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoothie-codex': {
      id: '/smoothie-codex'
      path: '/smoothie-codex'
      fullPath: '/smoothie-codex'
      preLoaderRoute: typeof SmoothieCodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-trees': {
      id: '/skill-trees'
      path: '/skill-trees'
      fullPath: '/skill-trees'
      preLoaderRoute: typeof SkillTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctuary': {
      id: '/sanctuary'
      path: '/sanctuary'
      fullPath: '/sanctuary'
      preLoaderRoute: typeof SanctuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathwork': {
      id: '/breathwork'
      path: '/breathwork'
      fullPath: '/breathwork'
      preLoaderRoute: typeof BreathworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alchemists-path': {
      id: '/alchemists-path'
      path: '/alchemists-path'
      fullPath: '/alchemists-path'
      preLoaderRoute: typeof AlchemistsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga/tools': {
      id: '/yoga/tools'
      path: '/tools'
      fullPath: '/yoga/tools'
      preLoaderRoute: typeof YogaToolsRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/start-here': {
      id: '/yoga/start-here'
      path: '/start-here'
      fullPath: '/yoga/start-here'
      preLoaderRoute: typeof YogaStartHereRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/resources': {
      id: '/yoga/resources'
      path: '/resources'
      fullPath: '/yoga/resources'
      preLoaderRoute: typeof YogaResourcesRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/pranayama': {
      id: '/yoga/pranayama'
      path: '/pranayama'
      fullPath: '/yoga/pranayama'
      preLoaderRoute: typeof YogaPranayamaRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/philosophy': {
      id: '/yoga/philosophy'
      path: '/philosophy'
      fullPath: '/yoga/philosophy'
      preLoaderRoute: typeof YogaPhilosophyRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/mastery': {
      id: '/yoga/mastery'
      path: '/mastery'
      fullPath: '/yoga/mastery'
      preLoaderRoute: typeof YogaMasteryRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/goals': {
      id: '/yoga/goals'
      path: '/goals'
      fullPath: '/yoga/goals'
      preLoaderRoute: typeof YogaGoalsRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/community': {
      id: '/yoga/community'
      path: '/community'
      fullPath: '/yoga/community'
      preLoaderRoute: typeof YogaCommunityRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/asanas': {
      id: '/yoga/asanas'
      path: '/asanas'
      fullPath: '/yoga/asanas'
      preLoaderRoute: typeof YogaAsanasRouteImport
      parentRoute: typeof YogaRoute
    }
    '/yoga/anatomy': {
      id: '/yoga/anatomy'
      path: '/anatomy'
      fullPath: '/yoga/anatomy'
      preLoaderRoute: typeof YogaAnatomyRouteImport
      parentRoute: typeof YogaRoute
    }
    '/breathwork/tools': {
      id: '/breathwork/tools'
      path: '/tools'
      fullPath: '/breathwork/tools'
      preLoaderRoute: typeof BreathworkToolsRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/techniques': {
      id: '/breathwork/techniques'
      path: '/techniques'
      fullPath: '/breathwork/techniques'
      preLoaderRoute: typeof BreathworkTechniquesRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/start-here': {
      id: '/breathwork/start-here'
      path: '/start-here'
      fullPath: '/breathwork/start-here'
      preLoaderRoute: typeof BreathworkStartHereRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/science': {
      id: '/breathwork/science'
      path: '/science'
      fullPath: '/breathwork/science'
      preLoaderRoute: typeof BreathworkScienceRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/resources': {
      id: '/breathwork/resources'
      path: '/resources'
      fullPath: '/breathwork/resources'
      preLoaderRoute: typeof BreathworkResourcesRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/mastery': {
      id: '/breathwork/mastery'
      path: '/mastery'
      fullPath: '/breathwork/mastery'
      preLoaderRoute: typeof BreathworkMasteryRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/goals': {
      id: '/breathwork/goals'
      path: '/goals'
      fullPath: '/breathwork/goals'
      preLoaderRoute: typeof BreathworkGoalsRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/community': {
      id: '/breathwork/community'
      path: '/community'
      fullPath: '/breathwork/community'
      preLoaderRoute: typeof BreathworkCommunityRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/breathwork/about': {
      id: '/breathwork/about'
      path: '/about'
      fullPath: '/breathwork/about'
      preLoaderRoute: typeof BreathworkAboutRouteImport
      parentRoute: typeof BreathworkRoute
    }
    '/yoga/goals/$goalId': {
      id: '/yoga/goals/$goalId'
      path: '/$goalId'
      fullPath: '/yoga/goals/$goalId'
      preLoaderRoute: typeof YogaGoalsGoalIdRouteImport
      parentRoute: typeof YogaGoalsRoute
    }
    '/yoga/asanas/$slug': {
      id: '/yoga/asanas/$slug'
      path: '/$slug'
      fullPath: '/yoga/asanas/$slug'
      preLoaderRoute: typeof YogaAsanasSlugRouteImport
      parentRoute: typeof YogaAsanasRoute
    }
    '/breathwork/techniques/traditions': {
      id: '/breathwork/techniques/traditions'
      path: '/traditions'
      fullPath: '/breathwork/techniques/traditions'
      preLoaderRoute: typeof BreathworkTechniquesTraditionsRouteImport
      parentRoute: typeof BreathworkTechniquesRoute
    }
    '/breathwork/techniques/$slug': {
      id: '/breathwork/techniques/$slug'
      path: '/$slug'
      fullPath: '/breathwork/techniques/$slug'
      preLoaderRoute: typeof BreathworkTechniquesSlugRouteImport
      parentRoute: typeof BreathworkTechniquesRoute
    }
    '/breathwork/goals/$goalId': {
      id: '/breathwork/goals/$goalId'
      path: '/$goalId'
      fullPath: '/breathwork/goals/$goalId'
      preLoaderRoute: typeof BreathworkGoalsGoalIdRouteImport
      parentRoute: typeof BreathworkGoalsRoute
    }
  }
}

interface BreathworkGoalsRouteChildren {
  BreathworkGoalsGoalIdRoute: typeof BreathworkGoalsGoalIdRoute
}

const BreathworkGoalsRouteChildren: BreathworkGoalsRouteChildren = {
  BreathworkGoalsGoalIdRoute: BreathworkGoalsGoalIdRoute,
}

const BreathworkGoalsRouteWithChildren = BreathworkGoalsRoute._addFileChildren(
  BreathworkGoalsRouteChildren,
)

interface BreathworkTechniquesRouteChildren {
  BreathworkTechniquesSlugRoute: typeof BreathworkTechniquesSlugRoute
  BreathworkTechniquesTraditionsRoute: typeof BreathworkTechniquesTraditionsRoute
}

const BreathworkTechniquesRouteChildren: BreathworkTechniquesRouteChildren = {
  BreathworkTechniquesSlugRoute: BreathworkTechniquesSlugRoute,
  BreathworkTechniquesTraditionsRoute: BreathworkTechniquesTraditionsRoute,
}

const BreathworkTechniquesRouteWithChildren =
  BreathworkTechniquesRoute._addFileChildren(BreathworkTechniquesRouteChildren)

interface BreathworkRouteChildren {
  BreathworkAboutRoute: typeof BreathworkAboutRoute
  BreathworkCommunityRoute: typeof BreathworkCommunityRoute
  BreathworkGoalsRoute: typeof BreathworkGoalsRouteWithChildren
  BreathworkMasteryRoute: typeof BreathworkMasteryRoute
  BreathworkResourcesRoute: typeof BreathworkResourcesRoute
  BreathworkScienceRoute: typeof BreathworkScienceRoute
  BreathworkStartHereRoute: typeof BreathworkStartHereRoute
  BreathworkTechniquesRoute: typeof BreathworkTechniquesRouteWithChildren
  BreathworkToolsRoute: typeof BreathworkToolsRoute
}

const BreathworkRouteChildren: BreathworkRouteChildren = {
  BreathworkAboutRoute: BreathworkAboutRoute,
  BreathworkCommunityRoute: BreathworkCommunityRoute,
  BreathworkGoalsRoute: BreathworkGoalsRouteWithChildren,
  BreathworkMasteryRoute: BreathworkMasteryRoute,
  BreathworkResourcesRoute: BreathworkResourcesRoute,
  BreathworkScienceRoute: BreathworkScienceRoute,
  BreathworkStartHereRoute: BreathworkStartHereRoute,
  BreathworkTechniquesRoute: BreathworkTechniquesRouteWithChildren,
  BreathworkToolsRoute: BreathworkToolsRoute,
}

const BreathworkRouteWithChildren = BreathworkRoute._addFileChildren(
  BreathworkRouteChildren,
)

interface YogaAsanasRouteChildren {
  YogaAsanasSlugRoute: typeof YogaAsanasSlugRoute
}

const YogaAsanasRouteChildren: YogaAsanasRouteChildren = {
  YogaAsanasSlugRoute: YogaAsanasSlugRoute,
}

const YogaAsanasRouteWithChildren = YogaAsanasRoute._addFileChildren(
  YogaAsanasRouteChildren,
)

interface YogaGoalsRouteChildren {
  YogaGoalsGoalIdRoute: typeof YogaGoalsGoalIdRoute
}

const YogaGoalsRouteChildren: YogaGoalsRouteChildren = {
  YogaGoalsGoalIdRoute: YogaGoalsGoalIdRoute,
}

const YogaGoalsRouteWithChildren = YogaGoalsRoute._addFileChildren(
  YogaGoalsRouteChildren,
)

interface YogaRouteChildren {
  YogaAnatomyRoute: typeof YogaAnatomyRoute
  YogaAsanasRoute: typeof YogaAsanasRouteWithChildren
  YogaCommunityRoute: typeof YogaCommunityRoute
  YogaGoalsRoute: typeof YogaGoalsRouteWithChildren
  YogaMasteryRoute: typeof YogaMasteryRoute
  YogaPhilosophyRoute: typeof YogaPhilosophyRoute
  YogaPranayamaRoute: typeof YogaPranayamaRoute
  YogaResourcesRoute: typeof YogaResourcesRoute
  YogaStartHereRoute: typeof YogaStartHereRoute
  YogaToolsRoute: typeof YogaToolsRoute
}

const YogaRouteChildren: YogaRouteChildren = {
  YogaAnatomyRoute: YogaAnatomyRoute,
  YogaAsanasRoute: YogaAsanasRouteWithChildren,
  YogaCommunityRoute: YogaCommunityRoute,
  YogaGoalsRoute: YogaGoalsRouteWithChildren,
  YogaMasteryRoute: YogaMasteryRoute,
  YogaPhilosophyRoute: YogaPhilosophyRoute,
  YogaPranayamaRoute: YogaPranayamaRoute,
  YogaResourcesRoute: YogaResourcesRoute,
  YogaStartHereRoute: YogaStartHereRoute,
  YogaToolsRoute: YogaToolsRoute,
}

const YogaRouteWithChildren = YogaRoute._addFileChildren(YogaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlchemistsPathRoute: AlchemistsPathRoute,
  BreathworkRoute: BreathworkRouteWithChildren,
  CommunityRoute: CommunityRoute,
  LibraryRoute: LibraryRoute,
  QuestsRoute: QuestsRoute,
  SanctuaryRoute: SanctuaryRoute,
  SkillTreesRoute: SkillTreesRoute,
  SmoothieCodexRoute: SmoothieCodexRoute,
  TaiChiLabRoute: TaiChiLabRoute,
  YogaRoute: YogaRouteWithChildren,
  YogaTherapyLabRoute: YogaTherapyLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
